{% set name = "gwtc_analysis" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Preferred for release builds: build from a tag
  git_url: https://github.com/danielsentenac/gwtc_analysis
  git_rev: v{{ version }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
requirements:
  host:
    - python 3.11
    - pip
    - setuptools
  run:
    - python >=3.10,<3.13
    - numpy
    - scipy
    - pandas
    - matplotlib
    - astropy
    - h5py
    - healpy
    - requests
    - tqdm
    - pyyaml
    - gwpy
    - gwosc
    - ligo.skymap
    - pesummary
    - minio

test:
  imports:
    - gwtc_analysis
  commands:
    - python -m gwtc_analysis.cli -h
    - python -m gwtc_analysis.cli search_skymaps -h
    - python -m gwtc_analysis.cli event_selection -h
    - python -m gwtc_analysis.cli catalog_statistics -h
    - python -m gwtc_analysis.cli parameters_estimation -h
  requires:
    - pip

about:
  summary: "GWTC Analysis: search skymaps, event selection, catalog statistics, and parameter estimation plotting"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielsentenac: daniel.sentenac@ligo.org

